version: '3.4'

services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  tasksEventDb:
    container_name: tasksEventDb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - tasksEventDb_data:/data/db
        
  tasksDb:
    container_name: tasksDb
    environment:
      SA_PASSWORD: yourStrongPassword123
      ACCEPT_EULA: Y
    restart: always
    ports:
      - "1434:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P yourStrongPassword123 -Q \"SELECT 1\"" ]
      interval: 5s
      
      timeout: 5s
      retries: 5
    volumes:
      - task-data:/var/opt/mssql
    
  groupsEventDb:
    container_name: groupsEventDb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - groupsEventDb_data:/data/db
  
  groupsDb:
    container_name: groupsDb
    environment:
      SA_PASSWORD: yourStrongPassword123
      ACCEPT_EULA: Y
    restart: always
    ports:
      - "1435:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P yourStrongPassword123 -Q \"SELECT 1\"" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - group-data:/var/opt/mssql
  
  identityDb:
    container_name: identityDb
    environment:
      SA_PASSWORD: yourStrongPassword123
      ACCEPT_EULA: Y
    restart: always
    ports:
      - "1436:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P yourStrongPassword123 -Q \"SELECT 1\"" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - identity-data:/var/opt/mssql
    
  rabbitmq:
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  apigateway:
    container_name: apigateway
    ports:
      - "8005:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Services:IdentityServerUrl=http://identityserver:80"
    depends_on: 
      - tasks.cmd.api
      - tasks.query.api
      - groups.query.api
      - groups.cmd.api
      - tasktracker.aggregators
  
  identityserver:
    container_name: identityserver
    ports:
      - "8080:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - ConnectionStrings__DefaultConnection=Server=identityDb;Database=IdentityDb;User=sa;Password=yourStrongPassword123;Encrypt=False;
      - "IdentityServer=http://identityserver:80"
      - "WebClientUrl=http://localhost:8010"
    depends_on:
      identityDb:
        condition: service_healthy
        
  tasks.cmd.api:
    container_name: tasks.cmd.api
    ports:
      - "8001:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Services:GroupQueryUrl=http://groups.query.api:80"
      - "Services:IdentityServerUrl=http://identityserver:80"
      - "DatabaseSettings:ConnectionString=mongodb://tasksEventDb:27017"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on: 
      rabbitmq:
         condition: service_healthy
      tasksEventDb:
        condition: service_started
    
  tasks.query.api:
    container_name: tasks.query.api
    ports:
      - "8002:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Services:IdentityServerUrl=http://identityserver:80"
      - ConnectionStrings__DefaultConnection=Server=tasksDb;Database=TaskDb;User=sa;Password=yourStrongPassword123;Encrypt=False;
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on: 
      tasksDb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

       
  groups.cmd.api:
    container_name: groups.cmd.api
    ports:
      - "8003:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Services:IdentityServerUrl=http://identityserver:80"
      - "DatabaseSettings:ConnectionString=mongodb://groupsEventDb"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      rabbitmq:
        condition: service_healthy
      groupsEventDb:
        condition: service_started
        
  groups.query.api:
    container_name: groups.query.api
    ports:
      - "8004:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Services:IdentityServerUrl=http://identityserver:80"
      - ConnectionStrings__DefaultConnection=Server=groupsDb;Database=GroupDb;User=sa;Password=yourStrongPassword123;Encrypt=False;
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      rabbitmq:
        condition: service_healthy
      groupsDb:
        condition: service_healthy
        
  tasktracker.aggregators:
    container_name: tasktracker.aggregators
    ports:
      - "8006:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Services:IdentityServerUrl=http://identityserver:80"
      - "Services:GroupQueryUrl=http://groups.query.api:80"
      - "Services:TaskQueryUrl=http://tasks.query.api:80"
    depends_on: 
      - groups.query.api
      - tasks.query.api
    
  webapp:
    container_name: webapp
    ports:
      - "8010:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "IdentityServerUrl=http://identityserver:80"
      - "ApiGatewayUrl=http://apigateway:80"
    depends_on:
      - apigateway
      - identityserver
        
  webstatus:
    container_name: webstatus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=Web
      - HealthChecksUI__HealthChecks__0__Uri=http://webapp/health
      - HealthChecksUI__HealthChecks__1__Name=Group.Cmd.Api
      - HealthChecksUI__HealthChecks__1__Uri=http://groups.cmd.api/health
      - HealthChecksUI__HealthChecks__2__Name=groups.query.api
      - HealthChecksUI__HealthChecks__2__Uri=http://groups.query.api/health
      - HealthChecksUI__HealthChecks__3__Name=tasks.cmd.api
      - HealthChecksUI__HealthChecks__3__Uri=http://tasks.cmd.api/health
      - HealthChecksUI__HealthChecks__4__Name=tasks.query.api
      - HealthChecksUI__HealthChecks__4__Uri=http://tasks.query.api/health
      - HealthChecksUI__HealthChecks__5__Name=task.aggregator
      - HealthChecksUI__HealthChecks__5__Uri=http://tasktracker.aggregators/health
      
    ports:
      - "8011:80"