version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce
  
  tasksEventDb:
    image: mongo
  
  tasksDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  
  groupsEventDb:
    image: mongo    
  
  groupsDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  
  identityDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    
  rabbitmq:
    image: rabbitmq:3-management
    
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGateway/Dockerfile
  
  identityserver:
    image: identityserver
    build:
      context: .
      dockerfile: src/services/IdentityService/IdentityServer/Dockerfile
  
  tasks.cmd.api:
    image: tasks.cmd.api
    build:
      context: .
      dockerfile: src/services/TasksServices/Tasks.Cmd/Tasks.Cmd.Api/Dockerfile
      
  tasks.query.api:
    image: tasks.query.api
    build: 
      context: .
      dockerfile: src/services/TasksServices/Tasks.Query/Tasks.Query.Api/Dockerfile

  groups.cmd.api:
    image: groups.cmd.api
    build:
      context: .
      dockerfile: src/services/GroupServices/Groups.Cmd/Groups.Cmd.Api/Dockerfile
  
  groups.query.api:
    image: groups.query.api
    build:
      context: .
      dockerfile: src/services/GroupServices/Groups.Query/Groups.Query.Api/Dockerfile
  
  tasktracker.aggregators:
    image: tasktracker.aggregators
    build:
      context: .
      dockerfile: src/ApiGateways/TaskTracker.Aggregators/Dockerfile
  
  webapp:
    image: webapp
    build: 
      context: .
      dockerfile: src/Web/WebApp/Dockerfile

volumes:
  tasksEventDb_data:
  portainer_data:
  task-data:
  groupsEventDb_data:
  group-data:
  identity-data: