version: '3.4'

services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  tasksEventDb:
    container_name: tasksEventDb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - tasksEventDb_data:/data/db
        
  tasksDb:
    container_name: tasksDb
    environment:
      SA_PASSWORD: yourStrongPassword123
      ACCEPT_EULA: Y
    restart: always
    ports:
      - "1434:1433"
    volumes:
      - task-data:/var/opt/mssql
    
  groupsEventDb:
    container_name: groupsEventDb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - groupsEventDb_data:/data/db
  
  groupsDb:
    container_name: groupsDb
    environment:
      SA_PASSWORD: yourStrongPassword123
      ACCEPT_EULA: Y
    restart: always
    ports:
      - "1435:1433"
    volumes:
      - group-data:/var/opt/mssql
  
  rabbitmq:
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  apigateway:
    container_name: apigateway
    ports:
      - "8005:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Services:IdentityServerUrl=http://identityserver:80"
    depends_on: 
      - identityserver
      - tasks.cmd.api
      - tasks.query.api
      - groups.query.api
      - groups.cmd.api
      - tasktracker.aggregators
  
  identityserver:
    container_name: identityserver
    ports:
      - "8080:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "IdentityServer=http://identityserver:80"
      - "WebClientUrl=http://localhost:8010"
        
  tasks.cmd.api:
    container_name: tasks.cmd.api
    ports:
      - "8001:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Services:GroupQueryUrl=http://groups.query.api:80"
      - "Services:IdentityServerUrl=http://identityserver:80"
      - "DatabaseSettings:ConnectionString=mongodb://tasksEventDb:27017"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on: 
      - tasksEventDb
      - rabbitmq
      - groups.query.api
      - identityserver
    
  tasks.query.api:
    container_name: tasks.query.api
    ports:
      - "8002:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Services:IdentityServerUrl=http://identityserver:80"
      - ConnectionStrings__DefaultConnection=Server=tasksDb;Database=TaskDb;User=sa;Password=yourStrongPassword123;Encrypt=False;
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on: 
      - tasksDb
      - rabbitmq
      - identityserver
       
  groups.cmd.api:
    container_name: groups.cmd.api
    ports:
      - "8003:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Services:IdentityServerUrl=http://identityserver:80"
      - "DatabaseSettings:ConnectionString=mongodb://groupsEventDb"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - groupsEventDb
      - rabbitmq
      - identityserver
        
  groups.query.api:
    container_name: groups.query.api
    ports:
      - "8004:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Services:IdentityServerUrl=http://identityserver:80"
      - ConnectionStrings__DefaultConnection=Server=groupsDb;Database=GroupDb;User=sa;Password=yourStrongPassword123;Encrypt=False;
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - groupsDb
      - rabbitmq
      - identityserver
        
  tasktracker.aggregators:
    container_name: tasktracker.aggregators
    ports:
      - "8006:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Services:IdentityServerUrl=http://identityserver:80"
      - "Services:GroupQueryUrl=http://groups.query.api:80"
      - "Services:TaskQueryUrl=http://tasks.query.api:80"
    depends_on: 
      - identityserver
      - groups.query.api
      - tasks.query.api
    
  webapp:
    container_name: webapp
    ports:
      - "8010:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "IdentityServerUrl=http://identityserver:80"
      - "ApiGatewayUrl=http://apigateway:80"
    depends_on:
      - identityserver
      - apigateway